name: Format

on:
  push:
    branches: ["main", "master"]
  pull_request:

permissions:
  contents: read

jobs:
  black:
    name: Black formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Check formatting
        run: black --check .
